import { ThemeProvider } from "@/providers/theme-provider";
import { AppFooter } from "@/ui/layout/app-footer";
import { AppNavBar } from "@/ui/layout/app-nav-bar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} antialiased`}>
        <ThemeProvider>
          <AppNavBar />
          {children}
          <AppFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
